ALTER TABLE checkins
ADD COLUMN num_photos INT(11) NOT NULL DEFAULT '0',
ADD COLUMN num_comments INT(11) NOT NULL DEFAULT '0',
ADD COLUMN num_likes INT(11) NOT NULL DEFAULT '0',
ADD COLUMN num_scores INT(11) NOT NULL DEFAULT '0';

ALTER TABLE checkins
ADD COLUMN date_next_poll DATETIME DEFAULT NULL,
ADD COLUMN poll_interval INT(11) NOT NULL DEFAULT '0';
